### ISSUE TITLE
Entities are not deleting

### ISSUE THREAD

**Issue by polischukovik** [polischukovik/Harvester#1]
Wen clicking Remove on any of list elements nothing is happaning.
Tried this for FIelds, Points, Machines
![image](https://cloud.githubusercontent.com/assets/17601700/25165223/037c757e-24de-11e7-85cd-599f2dbbeb78.png)

Logs attached
[log.txt](https://github.com/polischukovik/Harvester/files/931951/log.txt)

**Comment by polischukovik** [comment]
Checking logs

**Comment by polischukovik** [comment]
fixed in new release v1.2

**Comment by chirchenko** [comment]
Hello dear developer.
I have a problem.
I do not know how to download the program in the same format as last time.
It was very convenient to download the archive and just after unpacking run the program.
Can I ask you to explain how to do it again for the new version?
I look forward to a response from you!

**Comment by polischukovik** [comment]
Dear Dmytro,


Thank you for contacting our Customer Support.

For us it is very important to receive such feedback as we want to make our
products better.


It is very easy to download from the archives of the last version of
program.

You should go to the project directory
<https://github.com/polischukovik/Harvester> and then click releases.

[image: Вбудоване зображення 1]

After that you can see a list of available releases.

Each release contains 3 downloadable archives.

2 archives with source code (.zip and .tar.gz) and one zip achieve with
compiled binaries.

[image: Вбудоване зображення 2]

Here is direct reference:
https://github.com/polischukovik/Harvester/releases/download/v1.2/harvester_v1.2.zip


Hope you’ll find this information helpful,

Please do not hesitate if you have further questions.

Regards,

Oleksii


28 квіт. 2017 р. 17:53 "chirchenko" <notifications@github.com> пише:
